version: '3.4'
services:
  frontend: # offloads api callbacks to a scalable service
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
  worker:
    build: 
      context: .
      dockerfile: lib/worker/Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mit-campus-decarbonization-worker:latest
    env_file:
      - .env
