create extension if not exists "vector" with schema "extensions";

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS "public";

ALTER SCHEMA "public" OWNER TO "pg_database_owner";

CREATE OR REPLACE FUNCTION "public"."get_buildings_in_scenario"(id bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN (SELECT building_id FROM "DemandScenarioBuilding" WHERE demand_scenario_id = id);
END;
$$;

ALTER FUNCTION "public"."get_buildings_in_scenario"(id bigint) OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."get_demand_scenario_id"(building_simulation_result_id bigint) RETURNS bigint
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN (SELECT demand_scenario_id FROM "DemandScenarioBuilding" WHERE id = building_simulation_result_id);
END;
$$;

ALTER FUNCTION "public"."get_demand_scenario_id"(building_simulation_result_id bigint) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."Building" (
    "id" bigint NOT NULL,
    "name" text,
    "gfa" real,
    "building_number" text,
    "group_level_1" text,
    "usage" text,
    "height" real,
    "year" smallint
);

ALTER TABLE "public"."Building" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."BuildingSimulationResult" (
    "id" bigint NOT NULL,
    "heating" extensions.vector(8760),
    "cooling" extensions.vector(8760),
    "lighting" extensions.vector(8760),
    "equipment" extensions.vector(8760),
    "fans" extensions.vector(8760),
    "pumps" extensions.vector(8760),
    "misc" extensions.vector(8760),
    "water" extensions.vector(8760)
);

ALTER TABLE "public"."BuildingSimulationResult" OWNER TO "postgres";

ALTER TABLE "public"."Building" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Building_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."DemandScenario" (
    "id" bigint NOT NULL,
    "name" text
);

ALTER TABLE "public"."DemandScenario" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."DemandScenarioBuilding" (
    "id" bigint NOT NULL,
    "building_id" bigint,
    "design_vector_id" bigint,
    "demand_scenario_id" bigint
);

ALTER TABLE "public"."DemandScenarioBuilding" OWNER TO "postgres";

ALTER TABLE "public"."DemandScenarioBuilding" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DemandScenarioBuilding_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."DemandScenario" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DemandScenario_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."DesignVector" (
    "id" bigint NOT NULL,
    "name" text
);

ALTER TABLE "public"."DesignVector" OWNER TO "postgres";

ALTER TABLE "public"."DesignVector" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DesignVector_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."PowerPlant" (
    "id" bigint NOT NULL,
    "name" text,
    "nominal_capacity" real,
    "nominal_cost" real,
    "nominal_emissions_factor" real
);

ALTER TABLE "public"."PowerPlant" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."PowerPlantScenario" (
    "id" bigint NOT NULL,
    "power_plant_id" bigint,
    "name" text,
    "emissions_factors" extensions.vector(8760),
    "cost_factors" extensions.vector(8760),
    "capacities" extensions.vector(8760)
);

ALTER TABLE "public"."PowerPlantScenario" OWNER TO "postgres";

ALTER TABLE "public"."PowerPlantScenario" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PowerPlantScenario_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."PowerPlant" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PowerPlant_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."SupplyScenario" (
    "id" bigint NOT NULL,
    "name" text
);

ALTER TABLE "public"."SupplyScenario" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."SupplyScenarioPlant" (
    "id" bigint NOT NULL,
    "plant_scenario_id" bigint,
    "supply_scenario_id" bigint
);

ALTER TABLE "public"."SupplyScenarioPlant" OWNER TO "postgres";

ALTER TABLE "public"."SupplyScenarioPlant" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."SupplyScenarioPlant_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."SupplyScenario" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."SupplyScenario_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."BuildingSimulationResult"
    ADD CONSTRAINT "BuildingSimulationResult_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Building"
    ADD CONSTRAINT "Building_building_number_key" UNIQUE ("building_number");

ALTER TABLE ONLY "public"."Building"
    ADD CONSTRAINT "Building_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."DemandScenarioBuilding"
    ADD CONSTRAINT "DemandScenarioBuilding_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."DemandScenario"
    ADD CONSTRAINT "DemandScenario_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."DesignVector"
    ADD CONSTRAINT "DesignVector_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."PowerPlantScenario"
    ADD CONSTRAINT "PowerPlantScenario_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."PowerPlant"
    ADD CONSTRAINT "PowerPlant_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."SupplyScenarioPlant"
    ADD CONSTRAINT "SupplyScenarioPlant_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."SupplyScenario"
    ADD CONSTRAINT "SupplyScenario_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."DemandScenarioBuilding"
    ADD CONSTRAINT "unique_building_demand_scenario_combination" UNIQUE ("building_id", "demand_scenario_id");

ALTER TABLE ONLY "public"."BuildingSimulationResult"
    ADD CONSTRAINT "BuildingSimulationResult_id_fkey" FOREIGN KEY (id) REFERENCES public."DemandScenarioBuilding"(id);

ALTER TABLE ONLY "public"."DemandScenarioBuilding"
    ADD CONSTRAINT "DemandScenarioBuilding_building_id_fkey" FOREIGN KEY (building_id) REFERENCES public."Building"(id);

ALTER TABLE ONLY "public"."DemandScenarioBuilding"
    ADD CONSTRAINT "DemandScenarioBuilding_demand_scenario_id_fkey" FOREIGN KEY (demand_scenario_id) REFERENCES public."DemandScenario"(id);

ALTER TABLE ONLY "public"."DemandScenarioBuilding"
    ADD CONSTRAINT "DemandScenarioBuilding_design_vector_id_fkey" FOREIGN KEY (design_vector_id) REFERENCES public."DesignVector"(id);

ALTER TABLE ONLY "public"."PowerPlantScenario"
    ADD CONSTRAINT "PowerPlantScenario_power_plant_id_fkey" FOREIGN KEY (power_plant_id) REFERENCES public."PowerPlant"(id);

ALTER TABLE ONLY "public"."SupplyScenarioPlant"
    ADD CONSTRAINT "SupplyScenarioPlant_plant_scenario_id_fkey" FOREIGN KEY (plant_scenario_id) REFERENCES public."PowerPlantScenario"(id);

ALTER TABLE ONLY "public"."SupplyScenarioPlant"
    ADD CONSTRAINT "SupplyScenarioPlant_supply_scenario_id_fkey" FOREIGN KEY (supply_scenario_id) REFERENCES public."SupplyScenario"(id);

ALTER TABLE "public"."Building" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."BuildingSimulationResult" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."DemandScenario" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."DemandScenarioBuilding" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."DesignVector" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."PowerPlant" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."PowerPlantScenario" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."SupplyScenario" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."SupplyScenarioPlant" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."get_buildings_in_scenario"(id bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."get_buildings_in_scenario"(id bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_buildings_in_scenario"(id bigint) TO "service_role";

GRANT ALL ON FUNCTION "public"."get_demand_scenario_id"(building_simulation_result_id bigint) TO "anon";
GRANT ALL ON FUNCTION "public"."get_demand_scenario_id"(building_simulation_result_id bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_demand_scenario_id"(building_simulation_result_id bigint) TO "service_role";

GRANT ALL ON TABLE "public"."Building" TO "anon";
GRANT ALL ON TABLE "public"."Building" TO "authenticated";
GRANT ALL ON TABLE "public"."Building" TO "service_role";

GRANT ALL ON TABLE "public"."BuildingSimulationResult" TO "anon";
GRANT ALL ON TABLE "public"."BuildingSimulationResult" TO "authenticated";
GRANT ALL ON TABLE "public"."BuildingSimulationResult" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Building_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Building_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Building_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."DemandScenario" TO "anon";
GRANT ALL ON TABLE "public"."DemandScenario" TO "authenticated";
GRANT ALL ON TABLE "public"."DemandScenario" TO "service_role";

GRANT ALL ON TABLE "public"."DemandScenarioBuilding" TO "anon";
GRANT ALL ON TABLE "public"."DemandScenarioBuilding" TO "authenticated";
GRANT ALL ON TABLE "public"."DemandScenarioBuilding" TO "service_role";

GRANT ALL ON SEQUENCE "public"."DemandScenarioBuilding_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DemandScenarioBuilding_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DemandScenarioBuilding_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."DemandScenario_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DemandScenario_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DemandScenario_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."DesignVector" TO "anon";
GRANT ALL ON TABLE "public"."DesignVector" TO "authenticated";
GRANT ALL ON TABLE "public"."DesignVector" TO "service_role";

GRANT ALL ON SEQUENCE "public"."DesignVector_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DesignVector_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DesignVector_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."PowerPlant" TO "anon";
GRANT ALL ON TABLE "public"."PowerPlant" TO "authenticated";
GRANT ALL ON TABLE "public"."PowerPlant" TO "service_role";

GRANT ALL ON TABLE "public"."PowerPlantScenario" TO "anon";
GRANT ALL ON TABLE "public"."PowerPlantScenario" TO "authenticated";
GRANT ALL ON TABLE "public"."PowerPlantScenario" TO "service_role";

GRANT ALL ON SEQUENCE "public"."PowerPlantScenario_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PowerPlantScenario_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PowerPlantScenario_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."PowerPlant_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PowerPlant_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PowerPlant_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."SupplyScenario" TO "anon";
GRANT ALL ON TABLE "public"."SupplyScenario" TO "authenticated";
GRANT ALL ON TABLE "public"."SupplyScenario" TO "service_role";

GRANT ALL ON TABLE "public"."SupplyScenarioPlant" TO "anon";
GRANT ALL ON TABLE "public"."SupplyScenarioPlant" TO "authenticated";
GRANT ALL ON TABLE "public"."SupplyScenarioPlant" TO "service_role";

GRANT ALL ON SEQUENCE "public"."SupplyScenarioPlant_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."SupplyScenarioPlant_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."SupplyScenarioPlant_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."SupplyScenario_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."SupplyScenario_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."SupplyScenario_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
